version: "3.8"

services:
  pubsub_emulator:
    image: google/cloud-sdk:emulators
    ports:
      - 8085:8085
    command: |
      gcloud beta emulators pubsub start --project=test-project --host-port=0.0.0.0:8085
